irida_workflow.xml now uses uuid for toolParameter toolId
phac-nml/irida-wf-ga2xml pull request #12
Opened 2020-05-15 22:16 UTC by JeffreyThiessen

This change makes the tool use the uuid instead of the tool_id ( `irida_workflow_structure.ga` ) when generating the `toolId` in `toolParameter ` for the `irida_workflow.xml` output file.

This allows for generating xml's that have multiple of the same tool, without crashing IRIDA.

2020-05-25 15:28 UTC, apetkau requested changes
Overall, this looks great @JeffreyThiessen. I'm really glad using the `uuid` works out in place of the tool id. Thanks so much for looking into this.  A few comments:

1. Can you make a `CHANGELOG.md` file which includes your changes?
2. Is it possible to make the change between using a `uuid` and `tool_id` optional? As in, controllable via a command-line parameter? That way people could reproduce the same behavior as the previous version.
3. Maybe this is something for a different PR, but could you add some basic info about how to compile this using Leiningen to the README file? That way we have it documented if we need to make additional modifications.
4. Similarly, could you add the Apache 2.0 LICENSE file to this repo (http://www.apache.org/licenses/LICENSE-2.0.txt). It mentions this license in the README file, but the LICENSE file is missing from the project.

2020-06-10 03:45 UTC, apetkau requested changes
This looks great. Thanks so much @JeffreyThiessen for addressing my issues.

1. I noticed that in the old version an ID for each workflow is automatically generated in the XML file:

   ```xml
     <id>350e3a53-5255-42c4-ad2f-6cb99524b6a3</id>
    ```

   However, in this code it leaves it as empty `<id/>`.

2. Also, could you update the version to **1.1.0** in `project.clj`? That we it will be ready for release when this is merged.

2020-06-10 03:45 UTC, apetkau commented on README.md
> +## Getting started with Leiningen
Could this part be moved to the end under a **Developer** heading to indicate that this is the way developers are expected to run the project?

2020-06-10 03:45 UTC, apetkau commented on README.md
> +- `-u`/`--uuid-as-toolid`: Use UUID when building tool_ids, needed for workflows with duplicate tools.
I'm wondering if we should maybe invert this? That is using uuid is the default and the option should be `--use-tool-name-as-id` or something like that?

2020-06-11 15:06 UTC, JeffreyThiessen commented on README.md
> +- `-u`/`--uuid-as-toolid`: Use UUID when building tool_ids, needed for workflows with duplicate tools.
I think if we invert this, then it would only make sense to change the parameter name to uuid as well, an all the code where this naming style exists in both wf-ga2xml and IRIDA, which would take a much longer time to do since we don't have anyone that knows clojure super well.

We could just flip the argument name around and the if else, but that's a pretty bad solution, since then the descriptions and things will no longer match, so I think I'd prefer that we kept the argument as `--uuid-as-toolid`

2020-06-11 15:32 UTC, apetkau commented on README.md
> +- `-u`/`--uuid-as-toolid`: Use UUID when building tool_ids, needed for workflows with duplicate tools.
I actually prefer the parameter name to stay as is. It ends up producing something that looks like:

```xml
    <parameter name="refseq_masher-1-adv.top_n_results" defaultValue="5">
      <toolParameter toolId="163f0c35-99ff-4b90-8f16-0a76eb44315b" parameterName="adv.top_n_results"/>
    </parameter>
...
    <parameter name="refseq_masher-2-adv.top_n_results" defaultValue="0">
      <toolParameter toolId="9f708acc-1c4f-4420-8d2c-49e2462a9340" parameterName="adv.top_n_results"/>
    </parameter>
```

That is, it makes it much easier to see what the particular parameter corresponds too in the XML file. Changing everything to the UUID would mean that someone would have to have open both the XML and the Galaxy `.ga` file and match entries up to figure out what parameter matched with what tool.

Note that the name in `<parameter name=..>` is only used to match up with the corresponding entry in the `messages_en.properties` file. It's not displayed anywhere.

My reason for wanting it inverted is that I believe in general, tools should just work with the default parameters for the most number of cases. Leaving `--uuid-as-toolid` as a parameter means that if anyone has duplicate tools in their workflow they will first have to run `irida-wf-ga2xml`, have it crash, dig through documentation (or post an issue) as to why, before figuring out they need to add `--uuid-as-toolid`. If using UUID's is enabled by default, then `irida-wf-ga2xml` will just work in more cases.

2020-06-18 18:17 UTC, JeffreyThiessen commented
I have updated the Readme file and project version number as requested.

On this other issue
> I noticed that in the old version an ID for each workflow is automatically generated in the XML file:
 > `<id>350e3a53-5255-42c4-ad2f-6cb99524b6a3</id>`

When I pull master and build the version 1.0 code, it also does not have the id generated, so I'm not sure how you are generating an id when you run it. That appears to be a bug unrelated to this change.

2020-06-18 18:55 UTC, apetkau commented
You're right that in master the `<id/>` is also left blank. This does work in the latest release (1.0.0). It looks like there's been updates to master since then which must have broken it (and it also leaves `<sequenceReadsPaired/>` blank instead of filling in the label). Changes to master since 1.0.0 (excluding this PR) https://github.com/phac-nml/irida-wf-ga2xml/compare/v1.0.0...8f8f4604265b9c45f4ce2bd8f1b165ffcfa5bc73

I will merge your code in (it looks great) but I think before a release we should fix up this issue so the tool works the same as previously.

2020-06-18 18:55 UTC, apetkau approved these changes

2020-06-18 18:55 UTC, merged